//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignXAMLZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string login { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypesUsersID { get; set; }
    
        public virtual TypesUser TypesUser { get; set; }
    }
}
